%  |**********************************************************************;
%  * Project           : MSci Project: PLAS-Smith-3
%  *
%  * Program name      : fit_Zdata.m
%  *
%  * Author            : Kelvin Chan
%  *
%  * Date created      : 20 MAR 2018
%  *
%  * Purpose           : Fits a set of data with Zernike Polynomials.
%  *
%  * Revision History  : v1.0
%  *
%  |**********************************************************************;

%%%%% INPUT %%%%%
%Name of the text file generated by 'shackhartmann.py' or 'read_xyz.py'
filename = 'focus.txt';

%Name of output text file which will contain fitted Zernike Polynomials.
output_zernike_filename = 'focus_zernike.txt';

%Number that represents a non-existence value
%no_data_val in 'read_xyz.py'. Not needed for 'shackhartmann.py' data
nan = 100.0;

%Length of the Z Matrix (N value of NxN matrix)
len = 17;

%Number of Zernike Polynomials to fit
numZernike = 1000;

%%%%%%%%%%%%%%%%%

[~, ~, Z] = read_Zdata(filename, len);

% Create array where all 'nan' values are found.
mask = Z ~= nan;

% Fitting format. 'Standard' is best.
format = 'standard';

% Fit data
N = ZernikeCalc([1:numZernike], Z, mask, format);

% Convert fitted polynomials into Z data
data = ZernikeCalc([1:numZernike], N, mask, format);
data = sum(data, 3);

% Create axes for data plot
X = linspace(-1, 1, len);
Y = X;
[X, Y] = meshgrid(X, Y);

% Plot data that is generated by the fitted polynomials
surf(X, Y, data)

% Write and store the Zernike polynomials into a text file.
writedata(output_zernike_filename, N)
disp(output_zernike_filename);
