%  |**********************************************************************;
%  * Project           : MSci Project: PLAS-Smith-3
%  *
%  * Program name      : read_Zdata.m
%  *
%  * Author            : Kelvin Chan
%  *
%  * Date created      : 21 MAR 2018
%  *
%  * Purpose           : Read data generated by the Python code.
%  *
%  * Revision History  : v1.0
%  *
%  |**********************************************************************;

function [X, Y, Z] = read_Zdata(filename, len)
% READ_ZERNIKE Read the wavefront data generated by 'shackhartmann.py' 
%              or 'read_xyz.py'.
%   filename: Name of text file containing the wavefront data, generated by
%             'shackhartmann.py' or 'read_xyz.py'.
%   len: The 1D size of the output Z matrix (N value of NxN matrix)

% Open textfile
file = fopen(filename, 'r');
format = '%f %f';

ilen = len*3;
jlen = len;

xyzsize = [jlen ilen];

%Read the values in the text file.
xyz = fscanf(file, format, xyzsize);

% Assign the values to the correct axis.
X = xyz(:, 1:len);
Y = xyz(:, len+1:len*2);
Z = xyz(:, 2*len+1:end);

% Transpose to have X, Y and Z values correctly positioned..
X = transpose(X);
Y = transpose(Y);
Z = transpose(Z);

fclose(filename)
end
